### ISSUE TITLE
Search under 3 characters

### ISSUE THREAD

**Issue by Lockee** [pektinasen/wald-der-tiere#1]
TabBarView is filtered with empty String with under 3 characters and updates full list, even when full list is already present

**Comment by pektinasen** [comment]
One problem is, that it reads the file every time it get's a change event from the text field. That's why we get a  flash of "Loading" every time. It's part of the "waiting for future" handling.
Maybe we can read the file on application startup and just keep the list of fish and bugs in memory. It's not that big anyway, right?

**Comment by pektinasen** [comment]
done: 5bf0a583c0590e2e3e4126c32e806a6419d0ab83
